---
version: "3.4"
services:
  ser2net2:
    container_name: ser2netv2
    image: ghcr.io/jippi/docker-ser2net
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/serial/by-id/usb-0658_0200-if00
