---
version: "3.4"
services:
  ser2net:
    container_name: ser2net
    image: ghcr.io/jippi/docker-ser2net
    restart: unless-stopped
    networks:
      - zwave
    volumes:
      - ./src/ser2net.yaml:/etc/ser2net/ser2net.yaml
    devices:
      - /dev/serial/by-id/usb-0658_0200-if00
networks:
  zwave:
