---
version: "3.4"
services:
  ser2net2:
    container_name: ser2net
    image: ghcr.io/theautomation/ser2net:main
    pull_policy: always
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/serial/by-id/usb-0658_0200-if00
