---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ser2net
  namespace: home-automation
  labels:
    app.kubernetes.io/name: ser2net
    app.kubernetes.io/instance: rfxcom
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: ser2net
      app.kubernetes.io/instance: rfxcom
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ser2net
        app.kubernetes.io/instance: rfxcom
    spec:
      containers:
        - name: ser2net
          image: "harbor.k8s.lan/k8s/ser2net:22"
          resources: {}
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
          ports:
            - containerPort: 3001
              protocol: TCP
          volumeMounts:
            - name: usb-rfxcom
              mountPath: /dev/ttyUSB0
      volumes:
        - name: usb-rfxcom
          hostPath:
            path: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1HCFOL-if00-port0
      nodeSelector:
        feature.node.kubernetes.io/usb-ff_0403_6001.present: "true"
      imagePullSecrets:
        - name: harbor-registry-creds

---
kind: Service
apiVersion: v1
metadata:
  name: ser2net
  namespace: home-automation
  labels:
    app.kubernetes.io/name: ser2net
    app.kubernetes.io/instance: rfxcom
spec:
  selector:
    app.kubernetes.io/name: ser2net
    app.kubernetes.io/instance: rfxcom
  ports:
    - name: http
      protocol: TCP
      port: 3001
      targetPort: 3001
